### ISSUE TITLE
Display does not include timezone offsets

### ISSUE THREAD

**Issue by Martin-Cox** [ua9msn/datetime#4]
When initially clicking on the field, the value is set to the current datetime. If the current datetime includes an offset, then the value includes that offset, but the display does not.

Example:
https://jsfiddle.net/ms9jh1d6/1/

Running this example in a timezone with an offset (e.g. UTC +01:00) at 14:00 results in the following:
- A "getTime" value of 13:00 + 01:00
- A display value of 13:00

Really it should have a display value of 14:00, as that is what the time is for the user.

**Comment by ua9msn** [comment]
This is not a bug. 
 Display the result as you do in the example gives you automatic timezone adjustment. 
The complexity of timezone management is up to you. Internally, the plugin uses UTC only. It accepts UTC,  it uses UTC,  it returns UTC.
Why it is so: For example, in Russia railroad use Moscow timezone, in  Kazakhstan it uses local timezone, at the same time aeroports give information in local timezone in both countries. Timezone transformation for all of this use-cases is a very peculiar thing and can not be handled by plugin. 
My suggestion to you would be in using [timezone.js](https://github.com/mde/timezone-js) library and manage offsets by yourself.

**Comment by creage** [comment]
I believe @Martin-Cox means, that Date returned by plugin does not match the one it displays. And I agree with him. No matter what way you handle timezones - the value and display should be the same.

**Comment by ua9msn** [comment]
Plugin always returns date in UTC TZ. 
If you notice, the time in the input is not in your local timezone, it is in UTC too.  
Even if you pass options
`$('selector').datetime({
                datetime: '01/03/1976 20:53',
                locale: 'ru',
                format: 'dd L yyyy HH:mm '
            });`
the input field will contain UTC.  `03 января 1976 15:53` , not `03 января 1976 20:53` (for my local TZ)
This is made on purpose i mentioned above, and will not be changed. 
If you want to get your local time - add your time offset manually. 
`const yourLocalOffet = (new Date()).getTimezoneOffset(); `

**Comment by creage** [comment]
@ua9msn well, I got your point, but from user perspective - it looks a bit confusing.

I'm passing in the `new Date()` value, which resolves into `Fri Apr 14 2017 20:12:37 GMT+0200`, depending on the timezone we are in. Please, note the **GMT+0200** part of it. 

And, your plugin displays not **20:12:37**, but a **18:12:37**, dropping down the time zone offset - which is really unexpected. I'd expect plugin to display me the datetime I've passed in - **20:12:37**, and return back the `Date` instance with the same TZ offset (**+2** in this particular example).

Couldn't we have a respect of initial TZ offset of the `Date` instance we pass in? Because, currently, to workaround that behavior, I have to **add/subtract** the TZ difference **before** providing my date to your plugin, and **subtract/add** same difference, when I read it back. These steps should be handled by the plugin natively, I believe.

**Comment by ua9msn** [comment]
Version 2 now has flag `useUTC`.
